name: "On-demand test"
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch or tag to test'
        required: true
        default: 'master'
        type: string

env:
  dependency: libelf-dev libdw-dev libaudit-dev libnuma-dev libpython3-dev libperl-dev libslang2-dev libunwind-dev libbfd-dev libiberty-dev libcap-dev libzstd-dev libbpf-dev libpfm4-dev libbabeltrace-dev libgtk2.0-dev libopencsd-dev binutils-dev systemtap-sdt-dev llvm clang asciidoc xmlto universal-ctags cscope

jobs:
  check-out:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the source code"
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - name: "Create a tarball"
        run: make perf-targz-src-pkg && mv perf-*.tar.gz perf-src.tar.gz

      - name: "Cache the tarball"
        uses: actions/cache@v3
        with:
          path: perf-src.tar.gz
          key: perf-${{ inputs.branch }}-tarball

  run-perf-test:
    runs-on: ubuntu-latest
    needs: check-out
    steps:
      - name: "Retrieve the tarball"
        uses: actions/cache@v3
        with:
          path: perf-src.tar.gz
          key: perf-${{ inputs.branch }}-tarball

      - name: "Extract the source"
        run: tar xf perf-src.tar.gz --strip-components=1

      - name: "Install dependencies"
        run: sudo apt-get install -y ${{ env.dependency }}

      - name: "Build it"
        run: make -C tools/perf

      - name: "Run perf test"
        run: sudo tools/perf/perf test

  build-test:
    runs-on: ubuntu-22.04
    needs: check-out
    steps:
      - name: "Retrieve the tarball"
        uses: actions/cache@v3
        with:
          path: perf-src.tar.gz
          key: perf-${{ inputs.branch }}-tarball

      - name: "Extract the source"
        run: tar xf perf-src.tar.gz --strip-components=1

      - name: "Install dependencies"
        run: sudo apt-get install -y  ${{ env.dependency }}

      - name: "Run build test"
        run: make -C tools/perf build-test

